@AuthApi_HostAddress = http://localhost:5222
@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIyNzI2MzU1ZS0yNmY3LTQ0OTMtOWYyZi02MzlmNGFkNThmYjgiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI3MjYzNTVlLTI2ZjctNDQ5My05ZjJmLTYzOWY0YWQ1OGZiOCIsImVtYWlsIjoiaW5kaXZpZHVhbEBleGFtcGxlLmNvbSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6ImluZGl2aWR1YWxAZXhhbXBsZS5jb20iLCJqdGkiOiJjODc0ZjNkZS00MDBlLTQ2M2ItYTI0YS1mMjJjMGJiZGMwYmIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJJbmRpdmlkdWFsVXNlciIsImV4cCI6MTc3ODU4NDcyMiwiaXNzIjoiQXV0aEFwaSIsImF1ZCI6IkF1dGhBcGlVc2VycyJ9.uVOSNomTL4pkH5eY_Ych7sdm4jjm0E5iG8t9gAH0VnI
@refreshToken = 7i2F5lp/pYVm5y+2vKZI8NV/VVtOmpnaffy5m2nI7eFQM17FdRuEEre/mIXOYl12ZtDJ66pMtU/JgMuo5RQCyQ==

POST {{AuthApi_HostAddress}}/api/auth/register
Content-Type: application/json

{
  "fullName": "Individual User",
  "email": "individual@example.com",
  "userName": "individualuser",
  "password": "P@ssw0rd1",
  "confirmPassword": "P@ssw0rd1",
  "role": "IndividualUser"
}

###

POST {{AuthApi_HostAddress}}/api/auth/login
Content-Type: application/json

{
  "email": "individual@example.com",
  "password": "P@ssw0rd1"
}

###

POST {{AuthApi_HostAddress}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

POST {{AuthApi_HostAddress}}/api/auth/logout
Authorization: Bearer {{accessToken}}
Content-Type: application/json

{
  "refreshToken": "{{refreshToken}}"
}

###

GET {{AuthApi_HostAddress}}/api/protected/me
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{AuthApi_HostAddress}}/api/protected/admin
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{AuthApi_HostAddress}}/api/protected/individual
Authorization: Bearer {{accessToken}}
Accept: application/json

###

GET {{AuthApi_HostAddress}}/api/protected/corporate
Authorization: Bearer {{accessToken}}
Accept: application/json
